config/routes.rb
TesisArduino::Application.routes.draw do
  
  post 'main/login', :as => :login
  get 'main/logout', :as => :logout
  
  get 'users/index', :as => :dashboard
  get 'users/list', :as => :users_list
  resources :users
  
  resources :profiles
  
  resources :sensor_groups
  resources :sensors do
    match '/value/:value', :action => :change_value, :on => :member, :as => "change"
    post 'arduino_render', :on => :member
  end
  
  namespace :alerts do
    get 'turn_off_main_alarm'
  end
  resources :alerts do
    post 'arduino_render', :on => :member
  end
  
  root :to => 'main#index'
end

app/models/user.rb
# encoding: utf-8
class User < ActiveRecord::Base
  belongs_to :profile
  attr_accessible :name, :lastname, :username, :password, :profile_id, :cellphone, :send_notification
  
  validates_presence_of :name, :message => "Debe ingresar el Nombre"
  validates_presence_of :lastname, :message => "Debe ingresar el Apellido"
  validates_presence_of :username, :message => "Debe ingresar el Nombre de Usuario"
  validates :username, :uniqueness => {:message => "El nombre de Usuario ingresado ya existe."}, :unless => Proc.new {|u| u.username != u.username_was}
  validates_presence_of :password, :message => "Debe ingresar la Contraseña", :on => :create
  validate :cellphone_for_notification
  
  before_save :generate_password_update
  
  scope :to_notificate, where("send_notification = 1 and cellphone is not null")

  def full_name
    "#{self.name} #{self.lastname}"
  end

  def authenticate(written_password)
  	Digest::SHA256.hexdigest(written_password + self.salt) == self.password
  end
  def have_access?(group, permission)
    access = self.profile.permissions[group][permission] rescue nil
    return true if access == "1"
    return false
  end

  protected
  def generate_password_update
    puts "generate_password_update"
    if self.password.blank?
      self.password = self.password_was
    else
     	self.change_password
    end
  end
  def change_password
    puts "change_password"
  	self.salt = Digest::SHA1.hexdigest(self.username + self.digest_key + Time.now.to_s) if self.salt.blank?
  	self.password = Digest::SHA256.hexdigest(self.password + self.salt)
  end
  def digest_key
    "queAburridoArbolPerroDibujito.I.013"
  end
  def cellphone_for_notification
    self.errors.add(:cellphone, "Debe completar el Celular para recibir notificaciones.") if self.send_notification? && self.cellphone.blank?
  end
end

app/controllers/users_controller.rb
# encoding: utf-8
class UsersController < ApplicationController
  before_filter :get_current_user
  before_filter :check_access, :except => :index
  add_breadcrumb "Inicio", :dashboard
  
  def index
    @sensor_groups = SensorGroup.all
  end
  
  def list    
    @users = User.includes(:profile)
    add_breadcrumb "Usuarios"
  end
  
  def new
    @user = User.new
    add_breadcrumb "Usuarios", :users_list
    add_breadcrumb "Crear"
  end
  def create
    if request.post?
      @user = User.new(params[:user])
      if @user.save
        flash[:notice] = "El usuario ha sido creado con éxito."
        redirect_to :users_list
      else
        add_breadcrumb "Usuarios", :users_list
        add_breadcrumb "Crear"
        render :action => :new
      end
    else
      redirect_to :new_user
    end
  end
  
  def edit
    @user = User.find(params[:id])
    add_breadcrumb "Usuarios", :users_list
    add_breadcrumb "Editar"
  end
  def update
    if request.put?
      @user = User.find(params[:id])
      if @user.update_attributes(params[:user])
        flash[:notice] = "El usuario ha sido actualizado con éxito."
        redirect_to edit_user_path(@user)
      else
        add_breadcrumb "Usuarios", :users_list
        add_breadcrumb "Editar"
        render :edit
      end
    else
      redirect_to :new_user
    end
  end
  
  def destroy
    if request.delete?
      @user = User.find(params[:id])
      if @user.destroy
        flash[:notice] = "El usuario ha sido eliminado con éxito."
      end
    end
    redirect_to :users_list
  end
  
  protected
  def check_access
    if @current_user
      if !@current_user.have_access?(:users, :manage)
        flash[:alert] = "Acceso Denegado. Su perfil no tiene permisos suficientes."
        redirect_to :dashboard
      end
    else
      flash[:alert] = "Acceso Denegado. Debe iniciar sesión."
      redirect_to :root
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h2>Editar Usuario</h2>
<%= display_base_errors(@user) %>
<%= form_for @user do |form| %>
<%= form.label :name, "Nombre" %>
<%= form.text_field :name %>
<%= form.label :lastname, "Apellido" %>
<%= form.text_field :lastname %>
<%= form.label :username, "Nombre de Usuario" %>
<%= form.text_field :username %>
<%= form.label :password, "Contraseña" %>
<%= form.password_field :password %>
<%= form.label :profile_id, "Perfil" %>
<%= form.select :profile_id, options_from_collection_for_select(Profile.all, :id, :name) %>
<%= form.label :cellphone, "Celular" %>
<div class="input-prepend">
	<span class="add-on">+595</span>
	<%= form.text_field :cellphone, :class => "input-medium" %>
</div>
<%= form.label(:send_notification, :class => "checkbox") do %>
	<%= form.check_box :send_notification %> Enviar notificaciones?
<% end %>
<p class="buttons">
	<button type="submit" class="btn btn-primary btn-large">Actualizar</button>
	<%= link_to("Eliminar", @user, :method => :delete, :class => "btn btn-large btn-danger", :confirm => "Está seguro que desea eliminar el usuario?") if @user.id != @current_user.id %>
</p>
<% end %>

app/views/users/index.html.erb
<ul class="unstyled text-center span4" id="sensor_groups">
	<% for sensor_group in @sensor_groups -%>
	<li><%= link_to sensor_group.name, sensor_group_path(sensor_group), :class => "btn btn-block btn-large" %></li>
	<% end -%>
</ul>

app/views/users/list.html.erb
<h2>Lista de Usuarios</h2>
<p><%= link_to "Crear nuevo", :new_user, :class => "btn" %></p>
<table class="table table-striped">
	<thead>
		<tr>
			<th>#</th>
			<th>Nombre</th>
			<th>Usuario</th>
			<th>Perfil</th>
		</tr>
	</thead>
	<tbody>
		<% for user in @users %>
		<tr>
			<td><%= user.id %></td>
			<td><%= link_to user.full_name, edit_user_path(user) %></td>
			<td><%= user.username %></td>
			<td><%= link_to user.profile.name, edit_profile_path(user.profile) %></td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/users/new.html.erb
<h2>Crear nuevo usuario</h2>
<%= display_base_errors(@user) %>
<%= form_for @user do |form| %>
<%= form.label :name, "Nombre" %>
<%= form.text_field :name %>
<%= form.label :lastname, "Apellido" %>
<%= form.text_field :lastname %>
<%= form.label :username, "Nombre de Usuario" %>
<%= form.text_field :username %>
<%= form.label :password, "Contraseña" %>
<%= form.password_field :password %>
<%= form.label :profile_id, "Perfil" %>
<%= form.select :profile_id, options_from_collection_for_select(Profile.all, :id, :name) %>
<%= form.label :cellphone, "Celular" %>
<div class="input-prepend">
	<span class="add-on">+595</span>
	<%= form.text_field :cellphone, :class => "input-medium" %>
</div>
<span class="help-block">Ejemplo: +5959XXXXXXXX</span>
<%= form.label(:send_notification, :class => "checkbox") do %>
	<%= form.check_box :send_notification %> Enviar notificaciones?
<% end %>
<p class="buttons"><button type="submit" class="btn btn-primary btn-large">Crear</button></p>
<% end %>